### ISSUE TITLE
Mistake in `.env-backup`

### ISSUE THREAD

**Issue by acornall** [digital-services-act/transparency-database#320]
Hi there! 

I just wanted to let you know that you may have accidentally left a valid [Microsoft Teams Webhook ](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using?tabs=cURL) in the `.env-backup` file [here](https://github.com/digital-services-act/transparency-database/blob/ab70433b351121d2f36d0227f480d9434174a39e/.env-backup#L72). 

There is some information [here](https://howtorotate.com/docs/tutorials/microsoftteams/) on rotating/revoking the secret.

CC: @robertbrowncc

**Comment by alainvd** [comment]
Hi,
Thanks for the messaging us about this discolsed Key. 
We have been able to rotate it thanks to your link.

Thanks a lot !
