### ISSUE TITLE
Empty csv files for platform specific full sized downloads

### ISSUE THREAD

**Issue by gr0esch** [digital-services-act/transparency-database#361]
Hi all,

I just discovered behaviour that seems like a bug to me.

When downloading platform specific full archives, e.g. Amazon only for the 14th of March, I'll get plenty of new zip files from the one downloaded zip file that only contain empty csvs.

E.g. ```https://dsa-sor-data-dumps.s3.eu-central-1.amazonaws.com/sor-amazon-2024-03-14-full.zip```

The sha1 has values match, so my copy seems to be intact. The file size of the zip match as well, but the csvs file size on my extracted folder is way below the size stated on the database page…

This does not make too much sense, right?

Best
Samuel

**Comment by alainvd** [comment]
Dear Samuel,

Automated processes generate the data export files, and occasionally, certain zip files may contain no data for a particular timeframe. Feel free to delete those files without concern.

I've thoroughly reviewed the statement of reasons count, and everything appears to be accurate.

As of March 14th, there were 317,383 statements of reasons available for the Amazon platform and the same amount in the csv files..

> ./sor-amazon-2024-03-14-full-00003-00000.csv has     4403 lines
> ./sor-amazon-2024-03-14-full-00019-00009.csv has     8595 lines
> ./sor-amazon-2024-03-14-full-00019-00008.csv has    18594 lines
> ./sor-amazon-2024-03-14-full-00002-00007.csv has     7040 lines
> ./sor-amazon-2024-03-14-full-00002-00006.csv has     4490 lines
> ./sor-amazon-2024-03-14-full-00002-00004.csv has     6011 lines
> ./sor-amazon-2024-03-14-full-00002-00005.csv has     8845 lines
> ./sor-amazon-2024-03-14-full-00025-00003.csv has      429 lines
> ./sor-amazon-2024-03-14-full-00002-00001.csv has    12127 lines
> ./sor-amazon-2024-03-14-full-00002-00000.csv has    10437 lines
> ./sor-amazon-2024-03-14-full-00018-00009.csv has    14299 lines
> ./sor-amazon-2024-03-14-full-00002-00002.csv has    17024 lines
> ./sor-amazon-2024-03-14-full-00002-00003.csv has     7499 lines
> ./sor-amazon-2024-03-14-full-00018-00008.csv has    14177 lines
> ./sor-amazon-2024-03-14-full-00018-00005.csv has     8638 lines
> ./sor-amazon-2024-03-14-full-00018-00004.csv has     5260 lines
> ./sor-amazon-2024-03-14-full-00018-00006.csv has    10726 lines
> ./sor-amazon-2024-03-14-full-00018-00007.csv has    14560 lines
> ./sor-amazon-2024-03-14-full-00018-00003.csv has     3273 lines
> ./sor-amazon-2024-03-14-full-00002-00008.csv has    14919 lines
> ./sor-amazon-2024-03-14-full-00002-00009.csv has    14602 lines
> ./sor-amazon-2024-03-14-full-00018-00002.csv has     9055 lines
> ./sor-amazon-2024-03-14-full-00018-00000.csv has    10031 lines
> ./sor-amazon-2024-03-14-full-00018-00001.csv has     8786 lines
> ./sor-amazon-2024-03-14-full-00019-00005.csv has     7663 lines
> ./sor-amazon-2024-03-14-full-00019-00004.csv has    12380 lines
> ./sor-amazon-2024-03-14-full-00019-00006.csv has    14949 lines
> ./sor-amazon-2024-03-14-full-00019-00007.csv has    13859 lines
> ./sor-amazon-2024-03-14-full-00019-00003.csv has     5335 lines
> ./sor-amazon-2024-03-14-full-00019-00002.csv has     4386 lines
> ./sor-amazon-2024-03-14-full-00017-00009.csv has     2829 lines
> ./sor-amazon-2024-03-14-full-00019-00000.csv has    13682 lines
> ./sor-amazon-2024-03-14-full-00019-00001.csv has     8480 lines
> TOTAL LINES COUNTED: 317383

**Comment by gr0esch** [comment]
Hi @alainvd – thanks for the quick response, I replicated your count and can confirm that… 

I just wondered about all the empty files, but will just ignore them then. Thanks for the quick support!

```
File: sor-amazon-2024-03-14-full-00011-00000.csv, Lines: 0
File: sor-amazon-2024-03-14-full-00005-00000.csv, Lines: 0
File: sor-amazon-2024-03-14-full-00024-00000.csv, Lines: 0
File: sor-amazon-2024-03-14-full-00030-00000.csv, Lines: 0
File: sor-amazon-2024-03-14-full-00008-00000.csv, Lines: 0
File: sor-amazon-2024-03-14-full-00029-00000.csv, Lines: 0
File: sor-amazon-2024-03-14-full-00022-00000.csv, Lines: 0
File: sor-amazon-2024-03-14-full-00036-00000.csv, Lines: 0
File: sor-amazon-2024-03-14-full-00017-00000.csv, Lines: 0
File: sor-amazon-2024-03-14-full-00003-00000.csv, Lines: 4403
File: sor-amazon-2024-03-14-full-00019-00009.csv, Lines: 8595
File: sor-amazon-2024-03-14-full-00019-00008.csv, Lines: 18594
File: sor-amazon-2024-03-14-full-00004-00000.csv, Lines: 0
File: sor-amazon-2024-03-14-full-00010-00000.csv, Lines: 0
File: sor-amazon-2024-03-14-full-00002-00007.csv, Lines: 7040
File: sor-amazon-2024-03-14-full-00002-00006.csv, Lines: 4490
File: sor-amazon-2024-03-14-full-00031-00000.csv, Lines: 0
File: sor-amazon-2024-03-14-full-00025-00000.csv, Lines: 0
File: sor-amazon-2024-03-14-full-00009-00000.csv, Lines: 0
File: sor-amazon-2024-03-14-full-00002-00004.csv, Lines: 6011
File: sor-amazon-2024-03-14-full-00002-00005.csv, Lines: 8845
File: sor-amazon-2024-03-14-full-00025-00003.csv, Lines: 429
File: sor-amazon-2024-03-14-full-00028-00000.csv, Lines: 0
File: sor-amazon-2024-03-14-full-00037-00000.csv, Lines: 0
File: sor-amazon-2024-03-14-full-00023-00000.csv, Lines: 0
File: sor-amazon-2024-03-14-full-00002-00001.csv, Lines: 12127
File: sor-amazon-2024-03-14-full-00002-00000.csv, Lines: 10437
File: sor-amazon-2024-03-14-full-00016-00000.csv, Lines: 0
File: sor-amazon-2024-03-14-full-00018-00009.csv, Lines: 14299
File: sor-amazon-2024-03-14-full-00002-00002.csv, Lines: 17024
File: sor-amazon-2024-03-14-full-00002-00003.csv, Lines: 7499
File: sor-amazon-2024-03-14-full-00018-00008.csv, Lines: 14177
File: sor-amazon-2024-03-14-full-00018-00005.csv, Lines: 8638
File: sor-amazon-2024-03-14-full-00026-00000.csv, Lines: 0
File: sor-amazon-2024-03-14-full-00032-00000.csv, Lines: 0
File: sor-amazon-2024-03-14-full-00013-00000.csv, Lines: 0
File: sor-amazon-2024-03-14-full-00018-00004.csv, Lines: 5260
File: sor-amazon-2024-03-14-full-00007-00000.csv, Lines: 0
File: sor-amazon-2024-03-14-full-00018-00006.csv, Lines: 10726
File: sor-amazon-2024-03-14-full-00018-00007.csv, Lines: 14560
File: sor-amazon-2024-03-14-full-00015-00000.csv, Lines: 0
File: sor-amazon-2024-03-14-full-00018-00003.csv, Lines: 3273
File: sor-amazon-2024-03-14-full-00001-00000.csv, Lines: 0
File: sor-amazon-2024-03-14-full-00002-00008.csv, Lines: 14919
File: sor-amazon-2024-03-14-full-00002-00009.csv, Lines: 14602
File: sor-amazon-2024-03-14-full-00020-00000.csv, Lines: 0
File: sor-amazon-2024-03-14-full-00018-00002.csv, Lines: 9055
File: sor-amazon-2024-03-14-full-00034-00000.csv, Lines: 0
File: sor-amazon-2024-03-14-full-00018-00000.csv, Lines: 10031
File: sor-amazon-2024-03-14-full-00018-00001.csv, Lines: 8786
File: sor-amazon-2024-03-14-full-00033-00000.csv, Lines: 0
File: sor-amazon-2024-03-14-full-00019-00005.csv, Lines: 7663
File: sor-amazon-2024-03-14-full-00027-00000.csv, Lines: 0
File: sor-amazon-2024-03-14-full-00019-00004.csv, Lines: 12380
File: sor-amazon-2024-03-14-full-00006-00000.csv, Lines: 0
File: sor-amazon-2024-03-14-full-00012-00000.csv, Lines: 0
File: sor-amazon-2024-03-14-full-00019-00006.csv, Lines: 14949
File: sor-amazon-2024-03-14-full-00019-00007.csv, Lines: 13859
File: sor-amazon-2024-03-14-full-00000-00000.csv, Lines: 0
File: sor-amazon-2024-03-14-full-00014-00000.csv, Lines: 0
File: sor-amazon-2024-03-14-full-00019-00003.csv, Lines: 5335
File: sor-amazon-2024-03-14-full-00019-00002.csv, Lines: 4386
File: sor-amazon-2024-03-14-full-00035-00000.csv, Lines: 0
File: sor-amazon-2024-03-14-full-00017-00009.csv, Lines: 2829
File: sor-amazon-2024-03-14-full-00021-00000.csv, Lines: 0
File: sor-amazon-2024-03-14-full-00019-00000.csv, Lines: 13682
File: sor-amazon-2024-03-14-full-00019-00001.csv, Lines: 8480
Total lines in all CSV files: 317383
```
