### ISSUE TITLE
create unique identifier field

### ISSUE THREAD

**Issue by alainvd** [digital-services-act/transparency-database#81]
allow platforms to add a unique identifier field.
We should have a unique index on platform + unique identifier to prevent duplicates

**Comment by robertbrowncc** [comment]
add this field in documentation (examples, errors, statement attributes)
add this field in the postman collections and files -- Rob

**Comment by robertbrowncc** [comment]
ensure that duplicates are blocked (controllers, try / catch, 422 Status Code custom error message)
ensure the field is required
test it

**Comment by robertbrowncc** [comment]
{
    "message": "The unique platform identifier is already in the database",
    "errors": {
        "platform_intern....": [
            "The unique platform identifier is already in the database"
        ]
    }
}

**Comment by robertbrowncc** [comment]
name suggestions: 

platform_unique_reference
platform_uuid
platform_internal_reference

**Comment by robertbrowncc** [comment]
I would store this is a concat string "pid|puid"

23|TW-345KI2O...
4|TK421

PID is platform Id
PUID is platform unique ide

and not make it a composite key. This way if we do have to transfer these SOR to the DSA Platform then we don't run into a problem with the DSA Platform having duplicates.

**Comment by robertbrowncc** [comment]
completed by @robertbrowncc
